name: languify

services:
  postgres:
    image: postgres:17-alpine
    container_name: languify_postgres
    environment:
      POSTGRES_USER: languify
      POSTGRES_PASSWORD: languify_dev
      POSTGRES_DB: languify_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
